#!/usr/bin/env bash

# Configure PATH
#  - These are line by line so that you can kill one without affecting the others.
#  - Lowest priority first, highest priority last.

export PATH=$HOME/bin:$PATH
export GOPATH="$HOME/go"


#export PATH=$PATH
#export PATH=/usr/local/sbin:$PATH
#export PATH=/usr/local/bin:$PATH
#export PATH=/usr/local/git/bin:$PATH
#export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
#export PATH=/usr/local/opt/llvm/bin:$PATH # mac only
#export PATH=$HOME/.deno/bin:$PATH
#export PATH=$HOME/.cargo/bin:$PATH
#export PATH=$HOME/code/go/bin:$PATH

# node developer #protip: add `node_modules/.bin` to your `PATH` so that all the bin scripts installed by npm modules are available on the cli from the root of the project directory, e.g., mocha, browserify, gulp.
# export PATH=node_modules/.bin:$PATH
