checkForUpdatesAutomatically: true
showFloatingNotifications: true
showMenuBarTitle: true
showMenuBarIcon: true
menuBarTitleTemplate: $WORKSPACE
menuBarDisplayAliases: ''
enableFocusManagement: false
centerCursorOnFocusChange: false
focusFrontmostWindow: false
enableSwipeGestures: true
swipeThreshold: 1.5e-1
restartAppOnWakeUp: false
swipeLeft3FingerAction: none
swipeRight3FingerAction: none
swipeUp3FingerAction: none
swipeDown3FingerAction: none
swipeLeft4FingerAction: nextWorkspace
swipeRight4FingerAction: previousWorkspace
swipeUp4FingerAction: none
swipeDown4FingerAction: none
displayMode: dynamic
centerCursorOnWorkspaceChange: false
changeWorkspaceOnAppAssign: true
activeWorkspaceOnFocusChange: true
autoAssignAppsToWorkspaces: false
autoAssignAlreadyAssignedApps: true
skipEmptyWorkspacesOnSwitch: false
keepUnassignedAppsOnSwitch: true
restoreHiddenAppsOnSwitch: false
enableWorkspaceTransitions: false
showRecentWorkspaceWhenActivatedTwice: false
workspaceTransitionDuration: 3e-1
workspaceTransitionDimming: 2e-1
loopWorkspaces: true
loopWorkspacesOnAllDisplays: false
switchWorkspaceOnCursorScreen: false
alternativeDisplays: ''
enablePictureInPictureSupport: true
switchWorkspaceWhenPipCloses: true
pipApps: []
pipScreenCornerOffset: 15
cornerHiddenApps: []
enableSpaceControl: true
showSpaceControl: cmd+delete
enableSpaceControlAnimations: false
enableSpaceControlTilesAnimations: false
spaceControlCurrentDisplayWorkspaces: false
spaceControlHideEmptyWorkspaces: false
spaceControlUpdateScreenshotsOnOpen: false
spaceControlNumberOfColumns: 0
enableWorkspaceSwitcher: true
showWorkspaceSwitcher: opt+tab
workspaceSwitcherShowScreenshots: true
workspaceSwitcherVisibleWorkspaces: 6
workspaceSwitcherSortByLastActivation: false
workspaceSwitcherCurrentDisplayWorkspaces: true
enableIntegrations: false
runScriptOnLaunch: ''
runScriptOnWorkspaceChange: sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE"
  DISPLAY="$DISPLAY"
runScriptAfterWorkspaceChange: ''
runScriptOnProfileChange: sketchybar --reload
